In [1]:
import numpy as np

In [2]:
[i for i in dir(np) if 'arr' in i]

['array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'broadcast_arrays',
 'chararray',
 'compare_chararrays',
 'get_array_wrap',
 'ndarray',
 'numarray',
 'recarray']

In [3]:
a=np.array([1,3,4,5,6,7])

In [4]:
a

array([1, 3, 4, 5, 6, 7])

In [5]:
b=([2,4,5,7])

In [6]:
print(type(b))

<class 'list'>


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
a.shape

(6,)

In [14]:
a1 = np.array([[2,4],[3,6],[9,4],[7,11]])

In [15]:
a1

array([[ 2,  4],
       [ 3,  6],
       [ 9,  4],
       [ 7, 11]])

In [16]:
print(type(a1))

<class 'numpy.ndarray'>


In [17]:
a1.shape


(4, 2)

In [18]:
a2 = np.array([[2,4,5],[3,6,1],[9,4,3],[7,11,9]])

In [20]:
a2

array([[ 2,  4,  5],
       [ 3,  6,  1],
       [ 9,  4,  3],
       [ 7, 11,  9]])

In [19]:
a2.shape

(4, 3)

In [21]:
a1

array([[ 2,  4],
       [ 3,  6],
       [ 9,  4],
       [ 7, 11]])

In [22]:
a1[0]  #only row no.

array([2, 4])

In [24]:
a1[0][1]   #both row andn column no.a2

4

In [25]:
a2

array([[ 2,  4,  5],
       [ 3,  6,  1],
       [ 9,  4,  3],
       [ 7, 11,  9]])

In [26]:
a2[2][2]

3

In [27]:
a2[0:2]

array([[2, 4, 5],
       [3, 6, 1]])

In [28]:
a2[0:2][0:1]

array([[2, 4, 5]])

In [30]:
a2[0:2,1:3]    #if we want a particular part of any array. we just give comma


array([[4, 5],
       [6, 1]])

In [31]:
a2[1,1]   #can do ths also instead of a[][]    #it is [row,col]

6

In [32]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((50,30))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
x=np.full((4,3),2)     #for a particular element here we have size and thn element.

In [40]:
x

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [41]:
y=np.full((4,3),5)

In [42]:
y

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [43]:
x+2     #can perform any operation eaisly

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [44]:
y+4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [48]:
z=y*4

In [49]:
z

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [50]:
x+y     #same size and datatype bhi compatible ho 

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [51]:
x/2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.add(x,y)     #can use add()

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
  n = int(input("enter dimension:"))

In [ ]:
 m = int(input("enter another dimension:"))